[package]
name = "dashcore-crypto"
version = { workspace = true }
authors = ["The Dash Core Developers"]
license = "CC0-1.0"
repository = "https://github.com/dashpay/rust-dashcore/"
description = "Cryptographic primitives shared by rust-dashcore crates."
categories = ["cryptography::cryptocurrencies"]
keywords = ["crypto", "dash", "bls", "secp256k1"]
edition = "2021"

[features]
default = []

bincode = ["dep:bincode", "dep:bincode_derive", "dashcore_hashes/bincode", "dash-network/bincode"]
bls = ["dash-pkc/bls", "dep:tracing"]
eddsa = ["dash-pkc/eddsa"]
serde = ["dep:serde", "dash-types/serde", "dashcore_hashes/serde", "dash-network/serde", "secp256k1/serde"]

[dependencies]
ambassador = { workspace = true }
base58ck = { version = "0.1.0" }
bincode = { workspace = true, optional = true }
bincode_derive = { workspace = true, optional = true }
dash-network = { path = "../dash-network" }
dash-pkc = { workspace = true, features = ["ecdsa", "std"] }
dash-types = { workspace = true, features = ["codec"] }
dashcore_hashes = { path = "../hashes" }
delegate = { workspace = true }
hex = { version = "0.4" }
internals = { path = "../internals", package = "dashcore-private" }
secp256k1 = { version = "0.33.1", features = ["recovery"] }
serde = { version = "1.0.219", default-features = false, features = [ "derive", "alloc" ], optional = true }
thiserror = "2"
tracing = { version = "0.1", optional = true }
zeroize = { version = "1.8" }

[lints.rust]
unexpected_cfgs = { level = "deny", check-cfg = ['cfg(bench)', 'cfg(fuzzing)', 'cfg(kani)'] }

[dev-dependencies]
bincode = { workspace = true, features = ["serde"] }
hex_lit = { version = "0.1.1", features = ["rust_v_1_46"] }
serde_json = { version = "1.0" }
